### ISSUE TITLE
[backstage] jira integration errors

### ISSUE THREAD

**Issue by jkleinlercher** [suxess-it/sx-cnp-oss#40]
die JIRA-Env-Variablen hab ich auf Dummy-Werte gesetzt. Die passen so nicht und führen zu Fehler in der UI. Oder können wir das JIRA-Plugin auch derweil raushauen?

im Log:
```
2024-04-05T07:48:11.247Z backstage error Request failed with status 500 [REDACTED] is not a legal HTTP header value type=errorHandler stack=TypeError: tbd
 is not a legal HTTP header value
    at validateValue (/opt/app-root/src/node_modules/node-fetch/lib/index.js:684:9)
    at Headers.append (/opt/app-root/src/node_modules/node-fetch/lib/index.js:836:3)
    at new Headers (/opt/app-root/src/node_modules/node-fetch/lib/index.js:761:11)
    at new Request (/opt/app-root/src/node_modules/node-fetch/lib/index.js:1231:19)
    at /opt/app-root/src/node_modules/node-fetch/lib/index.js:1449:19
    at new Promise (<anonymous>)
    at Object.fetch [as default] (/opt/app-root/src/node_modules/node-fetch/lib/index.js:1447:9)
    at VaultClient.callApi (/opt/app-root/src/node_modules/@backstage/plugin-vault-backend/dist/index.cjs.js:44:53)
    at /opt/app-root/src/node_modules/@backstage/plugin-vault-backend/dist/index.cjs.js:72:18
    at /opt/app-root/src/node_modules/p-limit/index.js:23:31
    at run (/opt/app-root/src/node_modules/p-limit/index.js:23:43)
    at /opt/app-root/src/node_modules/p-limit/index.js:45:20
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by jkleinlercher** [comment]
Jira Plugin removed
